package org.car2x.veins.modules.application.traci;  // Declaração do pacote em que a classe está localizada.

import org.car2z.veins.modules.application.ieee80211p.BaseWaveAppLayer;  // Importa a classe BaseWaveAppLayer do pacote org.car2z.veins.modules.application.ieee80211p.

simple RSUApp extends BaseWaveAppLayer  // Declaração da classe RSUApp que estende a classe BaseWaveAppLayer.
{
    @class(RSUApp);  // Anotação que indica que essa classe corresponde à classe RSUApp no script SUMO.
}
